name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-and-test:
        
        runs-on: macos-14
        
        timeout-minutes: 8

        steps:
        - uses: actions/checkout@v4

        - name: Select Xcode
          run: sudo xcode-select -switch /Applications/Xcode_15.4.app
      
        - name: Xcode version
          run: /usr/bin/xcodebuild -version
      
        - name: Build and Test
          run: xcodebuild clean build test -project OnlineFeed/OnlineFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
